# 💝 Поддержка проектов XDTeam

# GitHub Sponsors
github: [XDTeam, founder-username]

# Patreon
patreon: xdteam

# Ko-fi
ko_fi: xdteam

# Tidelift
# tidelift: npm/package-name

# Community Bridge
# community_bridge: project-name

# Liberapay
# liberapay: xdteam

# IssueHunt
# issuehunt: XDTeam

# Open Collective
open_collective: xdteam

# Cryptocurrency addresses
# bitcoin: 1A1B2C3D4E5F6G7H8I9J0K1L2M3N4O5P6Q7R8S9
# ethereum: 0x1234567890123456789012345678901234567890

# Custom funding links
custom: 
  - "https://xdteam.dev/support"
  - "https://www.paypal.com/paypalme/xdteam"
  - "https://boosty.to/xdteam"

