name: 🧹 Manage Stale Issues and PRs

on:
  schedule:
    - cron: '0 9 * * *'  # Run daily at 9 AM UTC
  workflow_dispatch:  # Allow manual trigger

jobs:
  stale:
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write
    
    steps:
      - name: Stale Issues and PRs
        uses: actions/stale@v9
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          
          # Days before marking as stale
          days-before-stale: 60
          days-before-close: 7
          
          # Messages
          stale-issue-message: |
            👋 Этот issue был автоматически помечен как устаревший из-за отсутствия активности в течение 60 дней.
            
            Если проблема все еще актуальна, пожалуйста:
            - 💬 Оставьте комментарий
            - 🔄 Обновите описание, если нужно
            - 🏷️ Добавьте метку `keep-open`, если issue должен остаться открытым
            
            Если активность не будет возобновлена в течение 7 дней, issue будет автоматически закрыт.
            
            Спасибо за ваш вклад! 🙏
            
          stale-pr-message: |
            👋 Этот Pull Request был автоматически помечен как устаревший из-за отсутствия активности в течение 60 дней.
            
            Если PR все еще актуален, пожалуйста:
            - 💬 Оставьте комментарий
            - 🔄 Обновите ветку с последними изменениями
            - 🏷️ Добавьте метку `keep-open`, если PR должен остаться открытым
            
            Если активность не будет возобновлена в течение 7 дней, PR будет автоматически закрыт.
            
            Спасибо за ваш вклад! 🙏
            
          close-issue-message: |
            🔒 Этот issue был автоматически закрыт из-за отсутствия активности.
            
            Если проблема все еще актуальна, не стесняйтесь переоткрыть его или создать новый issue с обновленной информацией.
            
            Спасибо за понимание! 💜
            
          close-pr-message: |
            🔒 Этот Pull Request был автоматически закрыт из-за отсутствия активности.
            
            Если изменения все еще актуальны, не стесняйтесь переоткрыть PR или создать новый с обновленным кодом.
            
            Спасибо за вклад! 💜
          
          # Labels
          stale-issue-label: '⏰ stale'
          stale-pr-label: '⏰ stale'
          exempt-issue-labels: 'pinned,security,keep-open,priority-high,priority-critical'
          exempt-pr-labels: 'pinned,security,keep-open,priority-high,priority-critical,work-in-progress'
          
          # Additional settings
          ascending: true
          operations-per-run: 50
          remove-stale-when-updated: true
          
          # Different timings for different labels
          exempt-all-issue-assignees: false
          exempt-all-pr-assignees: false

