name: 🎉 Welcome New Contributors

on:
  issues:
    types: [opened]
  pull_request_target:
    types: [opened]

jobs:
  welcome:
    if: github.event.action == 'opened'
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write
    
    steps:
      - name: Welcome new contributor
        uses: actions/github-script@v7
        with:
          script: |
            const { owner, repo } = context.repo;
            const { actor } = context;
            const eventType = context.eventName;
            
            // Check if user is first-time contributor
            const { data: contributions } = await github.rest.repos.listContributors({
              owner,
              repo,
              per_page: 100
            });
            
            const isFirstTime = !contributions.find(contributor => 
              contributor.login === actor
            );
            
            if (!isFirstTime) return;
            
            let welcomeMessage, emoji;
            
            if (eventType === 'issues') {
              emoji = '🐛';
              welcomeMessage = `# ${emoji} Добро пожаловать в XDTeam!
            
            Привет @${actor}! 👋
            
            Спасибо за создание вашего первого issue в нашем проекте! Мы ценим ваш вклад в улучшение наших продуктов.
            
            ## 📋 Что дальше?
            
            - Наша команда рассмотрит ваш issue в ближайшее время
            - Если нужна дополнительная информация, мы попросим её в комментариях
            - Следите за обновлениями - мы стараемся отвечать быстро!
            
            ## 🤝 Хотите внести больший вклад?
            
            - 📖 Изучите наше [руководство по участию](https://github.com/${owner}/.github/blob/main/CONTRIBUTING.md)
            - 💬 Присоединяйтесь к нашему [Telegram чату](https://t.me/xdteam_dev)
            - 🌟 Поставьте звезду проектам, которые вам нравятся
            - 📢 Расскажите друзьям о XDTeam
            
            **Добро пожаловать в сообщество! 🚀**`;
            } else {
              emoji = '🎉';
              welcomeMessage = `# ${emoji} Ваш первый Pull Request!
            
            Привет @${actor}! 👋
            
            Спасибо за ваш первый Pull Request в XDTeam! Это важный шаг, и мы ценим ваше желание улучшить наши проекты.
            
            ## 🔍 Процесс ревью
            
            - Наша команда проведет ревью вашего кода
            - Мы можем попросить внести изменения - это нормальная часть процесса
            - Используйте комментарии для обсуждения и вопросов
            
            ## ✅ Убедитесь, что:
            
            - [ ] Ваш код соответствует нашим [стандартам](https://github.com/${owner}/.github/blob/main/CONTRIBUTING.md#стандарты-разработки)
            - [ ] Все проверки проходят успешно
            - [ ] PR описание заполнено по шаблону
            - [ ] Добавлены тесты (если применимо)
            
            ## 🤝 Присоединяйтесь к сообществу!
            
            - 💬 [Telegram чат разработчиков](https://t.me/xdteam_dev)
            - 📧 [Email для вопросов](mailto:support@xdteam.dev)
            - 🐙 [Другие проекты XDTeam](https://github.com/${owner})
            
            **Спасибо за ваш вклад! 🙏**`;
            }
            
            // Add comment
            if (eventType === 'issues') {
              await github.rest.issues.createComment({
                owner,
                repo,
                issue_number: context.issue.number,
                body: welcomeMessage
              });
              
              // Add welcome label
              await github.rest.issues.addLabels({
                owner,
                repo,
                issue_number: context.issue.number,
                labels: ['👋 first-time-contributor']
              });
            } else {
              await github.rest.pulls.createReview({
                owner,
                repo,
                pull_number: context.issue.number,
                body: welcomeMessage,
                event: 'COMMENT'
              });
              
              // Add welcome label
              await github.rest.issues.addLabels({
                owner,
                repo,
                issue_number: context.issue.number,
                labels: ['👋 first-time-contributor']
              });
            }

